---
- hosts: all
  become: yes
  tasks:
    - name: set /etc/hostname
      hostname:
        name: "{{ inventory_hostname }}"
    - name: set /etc/hosts
      include_role:
        name: DeepOps.hosts
      vars:
        hosts_add_ansible_managed_hosts: true
        hosts_entries:
            - name: provisioning-node.csc101.local
              ip: 192.168.199.242
              aliases:
                  - provisioning-node
                  - csc101.local
